### ISSUE TITLE
More creativity

### ISSUE THREAD

**Issue by spyke7** [MariiaSizova/breakfastapi#4]
Well done. I am looking forward that you will add more recipes. If you turn it on to an flask application (website using flask python library) it will be supercool. If any user comes to your website, you show the list of recipes from your api and they can select the recipe and you show all other things by fetching from your api. Well done

**Comment by MariiaSizova** [comment]
Hey thanks for the amazing ideas. That's true, I can return rendered html pages with FastApi and it would be more human friendly way to view the items! Thank you once again!
